Labs-EU4/lambda-door-client

src/App.css, src/components/Company/CompanyReview/CompanyReviewCard.jsx, src/components/Company/InterviewReviews/InterviewReviewList.jsx, src/components/Company/SalaryReviews/SalaryReviewsList.jsx, src/components/CompanySummaryCard.jsx, src/components/Layout/Search/CompanySearchCard.jsx, src/components/Layout/Search/InterviewSearchCard.jsx, src/components/Layout/Search/SalarySearchCard.jsx, src/components/MyReviews/Company/SmallReviewCard.jsx, src/components/MyReviews/Interview/SmallReviewCard.jsx, src/components/MyReviews/Salary/SmallSalaryReviewCard.jsx, src/components/UserDashboard/TopRated/TopRatedList.jsx, src/components/UserDashboard/UserLocationComp/ClosestLocationList.jsx
Hovering cards now performs better
=> Hover and round corners

src/components/CompanySummaryCard.jsx
Bug fix - Make ratings display on card
- [ X] New and existing unit tests pass locally with my changes
https://trello.com/c/pNYiq2aj
=> fixed ratings

src/components/CompanySummaryCard.jsx, src/components/UserDashboard/TopRated/TopRatedCard.jsx, src/components/UserDashboard/TopRated/TopRatedList.jsx, src/components/UserDashboard/UserLocationComp/ClosestLocationCard.jsx, src/components/UserDashboard/UserLocationComp/ClosestLocationList.jsx, src/pages/UserDashboard/UserDashboard.jsx
Re worked the home page layout 
https://trello.com/c/JS3c49Mb/31-rearrange-the-cards-on-the-homepage
=> dashboard-cards

src/components/Router/index.jsx, src/components/UserDashboard/TopRated/HighestRated.jsx, src/components/UserDashboard/TopRated/TopRatedList.jsx, src/pages/UserDashboard/UserDashboard.jsx
=> component created

package-lock.json, package.json
running failed tests only to make development faster also added types definition for jest
=> ⚡feat(test): faster tests by running failed tests only

src/pages/AddReview/AddReview.jsx, src/pages/AddReview/AddReview.test.js, src/pages/AddReview/__snapshots__/AddReview.test.js.snap
🧪test(reviews): test add review form
=> 🧪test(reviews): test add review form

src/pages/MyReviews/ManageReviews.test.js, src/pages/MyReviews/__snapshots__/ManageReviews.test.js.snap
Describe change or new feature here.
=> 🧪 test(reviews): test ManageReviews

src/components/MyReviews/InterviewReviews/DetailedReviewCard.test.jsx, src/components/MyReviews/InterviewReviews/__snapshots__/DetailedReviewCard.test.jsx.snap
Describe change or new feature here.
=> 🧪 test(reviews): test DetailedReviewCard

src/components/MyReviews/Interview/SmallReviewCard.test.jsx
Test added to smallReviewCard in interests.
> https://trello.com/c/cxT6Gozt/55-add-test-for-components-interests-smallreviewcard
=> (smallreviewcard): add test to smallreviewcard

src/components/MyReviews/Salary/DetailedSalaryReviewCard.test.js, src/components/MyReviews/Salary/__snapshots__/DetailedSalaryReviewCard.test.js.snap
🧪 test(reviews): test DetailedSalaryReviewCard
=> 🧪 test(reviews): test DetailedSalaryReviewCard

src/components/MyReviews/Salary/MySalaryReviewList.test.js, src/components/MyReviews/Salary/__snapshots__/MySalaryReviewList.test.js.snap
🧪 test(reviews): test MySalaryReviewList
=> 🧪 test(reviews): test MySalaryReviewList

src/components/Layout/SideNav/SideNav.test.js, src/components/Layout/SideNav/__snapshots__/SideNav.test.js.snap
=> 🧪 test(reviews): test SideNav

src/components/HighestSalaryCard.test.jsx
🧪 test(components): HighestSalaryCard
> https://trello.com/c/BDQJD61y/61-add-test-for-components-highestsalarycard
=> 🧪test(components): test HighestSalaryCard

src/components/CompanySummaryCard.test.jsx
🧪 test(components): test  CompanySummaryCard
> https://trello.com/c/QdvwN7g3/60-add-test-for-components-companysummarycard
=> 🧪test(components): test CompanySummaryCard

src/components/MyReviews/Interview/DetailedReviewCard.test.jsx
Add test to interests detailed review card.
> https://trello.com/c/K3jL7RMb/56-add-test-for-components-interviews-detailedreviewcard
=> test(interview)add test to interview DetailedReviewCard

src/components/MyReviews/Company/__tests__/CompanyReviewList.test.jsx
🧪 test(components): CompanyReviewList
> https://trello.com/c/SwwDFERv/62-add-test-for-components-companyreviewlist
=> 🧪  test(components): add test to CompanyReviewList

src/components/Company/SalaryReviews/SalaryReviewsList.test.jsx
🧪 test(components): SalaryReviewList
> https://trello.com/c/DZFBezxP/63-add-test-for-components-salaryreviewslist
=> 🧪 test(components): add test to SalaryReviewsList

src/components/Company/InterviewReviews/InterviewReviewList.test.jsx
🧪 test(components): InterviewReviewList
> https://trello.com/c/DUb0jwgs/64-add-test-for-components-interviewreviewlist
=> 🧪 test(components): add test to InterviewReviewList

src/components/Company/InterviewReviews/InterviewReviewDetails.test.jsx, src/components/Company/InterviewReviews/InterviewReviewList.test.jsx
🧪 test(components): InterviewReviewDetails
> https://trello.com/c/pyXi5xVv/65-add-test-for-components-interviewreviewdetails
=> 🧪 Test(components) interview review details

src/components/Company/SalaryReviews/SalaryReviewDetails.test.jsx
🧪 test(components):  SalaryReviewDetails
> https://trello.com/c/GfYxVWoo/66-add-test-for-components-salaryreviewdetails
=> 🧪test(components): add test for SalaryReviewDetails

src/components/CompanySummaryCard.jsx, src/pages/AddReview/AddReview.jsx
🐛fix(general): remove debug code, fix link
=> 🐛fix(general): remove debug code, fix link

src/components/AppInfoContainer.test.jsx
🧪 test(components): AppInfoConatainer
> https://trello.com/c/9AvKN0f2/73-add-test-to-components-appinfocontainer
=> 🧪 test(Components) add test to AppInfoConatainer

src/components/Company/CompanyReview/CompanyReviewCardDetails.test.jsx, src/components/MyReviews/Interview/InterviewReviewList.test.jsx
🧪 test(components/MyReviews): interview review list
> https://trello.com/c/qcy7VkK0/72-add-test-to-components-myrevies-interviewreviewlist
=> 🧪  Test my reviews interview review list

src/components/Company/CompanyReview/CompanyReviewCardDetails.test.jsx
🧪 test(components): CompanyReviewCardDetails
> https://trello.com/c/25VUmTn4/70-add-test-to-components-comanyreviewcarddetails
=> 🧪 test(components): add test to CompanyReviewCardDetails

src/components/Layout/SideNav/Avatar.test.jsx, src/components/Layout/SideNav/Interest.test.js, src/components/Layout/SideNav/__snapshots__/Avatar.test.jsx.snap, src/components/Layout/SideNav/__snapshots__/Interest.test.js.snap
Added test for  sidenav/avatar and interests.js
https://trello.com/c/feQGgTgE/71-add-test-to-src-components-layout-sidenav-interestjsx-and-avatarjs
=> Test sidenav/avatar and interests.js

package.json, src/components/Company/InterviewReviews/__snapshots__/InterviewReviewDetails.test.jsx.snap, src/components/Company/InterviewReviews/__snapshots__/InterviewReviewList.test.jsx.snap, src/components/Company/SalaryReviews/__snapshots__/SalaryReviewDetails.test.jsx.snap, src/components/Company/SalaryReviews/__snapshots__/SalaryReviewsList.test.jsx.snap, src/components/Layout/Search/CompanySearchCard.test.jsx, src/components/Layout/Search/DetailedInterviewSearchCard.test.jsx, src/components/Layout/Search/DetailedSalarySearchCard.test.jsx, src/components/Layout/Search/InterviewSearchCard.test.jsx, src/components/Layout/Search/SalarySearchCard.test.jsx, src/components/Layout/Search/Search.test.jsx, src/components/Layout/Search/SearchResults.test.jsx, src/components/Layout/Search/__snapshots__/CompanySearchCard.test.jsx.snap, src/components/Layout/Search/__snapshots__/DetailedInterviewSearchCard.test.jsx.snap, src/components/Layout/Search/__snapshots__/DetailedSalarySearchCard.test.jsx.snap, src/components/Layout/Search/__snapshots__/InterviewSearchCard.test.jsx.snap, src/components/Layout/Search/__snapshots__/SalarySearchCard.test.jsx.snap, src/components/Layout/Search/__snapshots__/Search.test.jsx.snap, src/components/Layout/Search/__snapshots__/SearchResults.test.jsx.snap, src/components/MyReviews/Company/__tests__/__snapshots__/CompanyReviewList.test.jsx.snap, src/components/MyReviews/Interview/__snapshots__/DetailedReviewCard.test.jsx.snap, src/components/__snapshots__/CompanySummaryCard.test.jsx.snap, src/components/__snapshots__/HighestSalaryCard.test.jsx.snap
🧪 test(search): test Layout --> Search
=> 🧪 test(search): test Layout --> Search
